OPENAI_API_KEY = "YOUR_API_KEY"
OPENAI_BASE_URL = "YOUR_BASE_URL"

MODEL_NAME = "MODEL_NAME_HERE"
EMBEDDING_MODEL_NAME = "MODEL_NAME_HERE"

CHUNK_SIZE = 500  # 默认为分割长度 500
CHUNK_OVERLAP = 50  # 默认为重叠长度 50

# FAISS 向量数据库保存路径
VECTOR_DB_PATH = "rag/vectorstore/faiss_index"
